import type { Promotion, Review, RoomType, ServiceItem } from '../types';

export const roomTypes: RoomType[] = [
  {
    id: 1,
    name: 'Standard',
    description: 'Phòng tiện nghi cơ bản, phù hợp cho kỳ nghỉ ngắn và công tác.',
    base_price: 850000,
    max_adults: 2,
    max_children: 1,
    amenities: ['WiFi', 'Điều hòa', 'Tivi'],
    image_url: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80',
    average_rating: 4.5,
    review_count: 85,
  },
  {
    id: 2,
    name: 'Deluxe',
    description: 'Không gian rộng hơn, thích hợp cho cặp đôi hoặc du lịch dài ngày.',
    base_price: 1200000,
    max_adults: 3,
    max_children: 2,
    amenities: ['WiFi', 'Điều hòa', 'Tivi', 'Ban công'],
    image_url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
    average_rating: 4.8,
    review_count: 142,
  },
  {
    id: 3,
    name: 'Family',
    description: 'Phòng gia đình với không gian nghỉ thoải mái cho cả trẻ em.',
    base_price: 1600000,
    max_adults: 4,
    max_children: 3,
    amenities: ['WiFi', 'Điều hòa', 'Tivi', 'Bồn tắm'],
    image_url: null,
    average_rating: 4.7,
    review_count: 68,
  },
  {
    id: 4,
    name: 'Suite',
    description: 'Suite cao cấp với thiết kế sang trọng, phục vụ trải nghiệm lưu trú đặc biệt.',
    base_price: 2300000,
    max_adults: 4,
    max_children: 2,
    amenities: ['WiFi', 'Điều hòa', 'Tivi', 'Ban công', 'Bồn tắm'],
    image_url: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80',
    average_rating: 4.9,
    review_count: 112,
  },
];

export const promotions: Promotion[] = [
  {
    id: 1,
    code: 'SAVE10',
    name: 'Ưu đãi mùa hè',
    description: 'Giảm cho khách đặt phòng từ 3 đêm trở lên.',
    discount_type: 'PERCENT',
    discount_value: 10,
    max_discount: 500000,
    valid_from: '2026-01-01',
    valid_to: '2026-12-31',
    is_active: true,
  },
  {
    id: 2,
    code: 'WELCOME200',
    name: 'Chào mừng khách mới',
    description: 'Giảm trực tiếp cho lần đặt đầu tiên.',
    discount_type: 'FIXED_AMOUNT',
    discount_value: 200000,
    max_discount: null,
    valid_from: '2026-09-01',
    valid_to: '2026-09-30',
    is_active: true,
  },
  {
    id: 3,
    code: 'EXPIRED99',
    name: 'Mã đã hết hạn',
    description: 'Mã này chỉ dùng để kiểm tra trạng thái hết hạn.',
    discount_type: 'PERCENT',
    discount_value: 15,
    max_discount: 300000,
    valid_from: '2026-01-01',
    valid_to: '2026-09-10',
    is_active: true,
  },
];

export const services: ServiceItem[] = [
  {
    id: 1,
    name: 'Đưa đón sân bay',
    description: 'Dịch vụ đưa đón với xe riêng và thuận tiện cho khách quốc tế.',
    price: 350000,
    unit: 'chuyến',
    is_active: true,
  },
  {
    id: 2,
    name: 'Giặt là',
    description: 'Dịch vụ giặt và ủi nhanh chóng, phù hợp cho khách lưu trú dài ngày.',
    price: 120000,
    unit: 'bộ',
    is_active: true,
  },
  {
    id: 3,
    name: 'Spa',
    description: 'Gói thư giãn với massage và làm đẹp cơ bản.',
    price: 450000,
    unit: 'buổi',
    is_active: false,
  },
  {
    id: 4,
    name: 'Ăn sáng',
    description: 'Menu ăn sáng đa dạng phục vụ trong nhà hàng.',
    price: 140000,
    unit: 'người',
    is_active: true,
  },
];

export const reviews: Review[] = [
  {
    id: 1,
    room_type_id: 1,
    customer_name: 'Lan Anh',
    rating: 5,
    comment: 'Phòng sạch, nhân viên thân thiện và vị trí thuận tiện.',
    is_hidden: false,
    room_type_name: 'Standard',
  },
  {
    id: 2,
    room_type_id: 2,
    customer_name: 'Minh Tuấn',
    rating: 4,
    comment: 'Phòng rộng, cửa sổ thoáng, giá hợp lý cho kỳ nghỉ.',
    is_hidden: false,
    room_type_name: 'Deluxe',
  },
  {
    id: 3,
    room_type_id: 3,
    customer_name: 'Hồng Yến',
    rating: 5,
    comment: 'Phòng gia đình rất thoải mái, phù hợp cho cả trẻ nhỏ.',
    is_hidden: false,
    room_type_name: 'Family',
  },
  {
    id: 4,
    room_type_id: 4,
    customer_name: 'Bảo Ngọc',
    rating: 5,
    comment: 'Suite đẹp và dịch vụ tốt, rất đáng trải nghiệm.',
    is_hidden: true,
    room_type_name: 'Suite',
  },
];
